### ISSUE TITLE
@minecraft/server的版本问题

### ISSUE THREAD

**Issue by HappyTigerV** [LoveCouple/serein#3]
安装的.d.ts的版本是stable，但是manifest.json中是beta
需要修改模板里的package.json中依赖项@minecraft/server模块的版本

**Comment by Lampese** [comment]
感谢反馈。

核查了一下确实是项目的问题，正在修。

**Comment by Lampese** [comment]
感谢反馈。

核查了一下确实是项目的问题，正在修。

**Comment by MeowShe** [comment]
Fixed in #5.
